app1/urls.py
from django.urls import path
from app1.views import *
app_name='any1'

urlpatterns=[
    path('first/',first,name='first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='any2'

urlpatterns=[
    path('second/',second,name='second'),
]

project20/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def first(request):
    return render(request,'first.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def second(request):
    return render(request,'second.html')

templates/first.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
    <link rel="stylesheet" href="{% static 'css/c2.css' %}">
</head>

<body>
    <center>
        <h1>vaisu movie</h1>
        <img src="{% static 'images/varisu.jpg' %}" alt="">
        <img src="{% static 'images/vijay.jpg' %}" alt="">
        <img src="{% static 'images/rashmika.jpg' %}" alt="">
        <h1>If you want Thunivu movie click below link</h1>
        <h1>
            <a href="{% url 'any2:second' %}">click here</a>
        </h1>
    </center>
</body>

</html>

templates/second.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
    <link rel="stylesheet" href="{% static 'css/c2.css' %}">
</head>

<body>
    <center>
        <h1>vaisu movie</h1>
        <img src="{% static 'images/thunivu.jpg' %}" alt="">
        <img src="{% static 'images/ajith.jpg' %}" alt="">
        <img src="{% static 'images/manju.jpg' %}" alt="">
        <h1>If you want Varisu movie click below link</h1>
        <h1>
            <a href="{% url 'any1:first' %}">click here</a>
        </h1>
    </center>
</body>

</html>